""" Chris Milson April 2020
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 −
22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of
D?

## Solution

In a similar manner to problem 42, we can determine quickly whether a number, t,
is pentagonal or not, by checking that 1 + 24t is a perfect square, and then the
extra condition that the square root of that is congruent to 5 modulo 6.

Answer : 5482660
"""
import math
from timeit import timeit

def pentagonal(n):
  return n * (3 * n - 1) // 2

def isPentagonal(n):
  return math.sqrt(1 + 24 * n) % 6 == 5

j = 1
found = False
while not found:
  J = pentagonal(j)
  for k in range(1, j):
    K = pentagonal(k)
    if isPentagonal(J + K) and isPentagonal(J - K):
      found = True
      print(J - K)
      break
  j+= 1